const catalog = [
	{
		id: 'good1',
		classes: 'salt',
		brend: 'Saltway',
		material: 'Дерево, пластик, гималайская соль',
		img: 'img/goods/good1.png',
		img1: 'img/goods/good1-1.png',
		img2: 'img/goods/good1-2.png',
		img3: 'img/goods/good1.png',
		img4: 'img/goods/good1-2.png',
		type: 'Солевая лампа',
		name: 'Кристалл',
		item: 'Настольный ночник',
		old_price: 1599,
		new_price: 899,
		description: 'Соляная лампа SL-35 (3-5 кг) - это светильник созданный самой природой из 100% натуральной гималайской соли. Гималайская соль обладает лечебными свойствами, является прекрасным ионизатором и очистителем воздуха, оказывает успокаивающее действие. Такая настольная лампа поможет погрузиться в глубокий расслабляющий сон ночью и с легкостью проснуться даже ранним утром. Будет отличным подарком, который украсит любой интерьер детской, спальни или гостиной комнаты. Ночник оснащен диммером, что позволяет регулировать яркость свечения лампы. Исходящий теплый, мягкий янтарный свет создаст уютную и комфортную обстановку в вашей комнате. Каждая лампа создана вручную, именно поэтому его форма, вес, цвет и рельеф уникальны. Патрон с цоколем Е14 легко вынимается из плафона, и замена лампочки происходит быстро и безопасно. В комплект поставки входит лампочка, инструкция по использованию на русском языке. Имеет Сертификат Соответствия ЕЭС.',
	},

	{
		id: 'good2',
		brend: 'My Smart Home',
		material: 'ABS-пластик, медь, фольгированное покрытие',
		classes: 'distance usb',
		img: 'img/goods/good2.png',
		type: 'Декоративный',
		name: 'Дерево',
		old_price: 3699,
		new_price: 1794,
	},

	{
		id: 'good3',
		brend: 'UNIHIT',
		material: 'Пластик',
		classes: 'baby three_d distance usb',
		img: 'img/goods/good3.png',
		type: '3D-ночник',
		name: 'Луна',
		old_price: 1335,
		new_price: 870,
	},

	{
		id: 'good4',
		brend: 'Le Romarin',
		material: 'ABS-пластик',
		classes: 'projector usb',
		img: 'img/goods/good4.png',
		type: 'Проектор',
		name: 'Ночное небо',
		old_price: 5309,
		new_price: 2410,
	},

	{
		id: 'good5',
		brend: 'Neon-Night',
		material: 'ПВХ',
		classes: 'portable',
		img: 'img/goods/good5.png',
		type: 'Декоративный',
		name: 'Фонарь',
		old_price: 1814,
		new_price: 598,
	},

	{
		id: 'good6',
		brend: 'Rexant',
		material: 'Пластик, светодиоды',
		classes: 'socket',
		img: 'img/goods/good6.png',
		type: 'Розеточный',
		name: 'Бабочка',
		old_price: 302,
		new_price: 182,
	},

	{
		id: 'good7',
		brend: 'Мир удивительных товаров',
		material: 'Стекло, ABS-пластик',
		classes: 'three_d distance',
		img: 'img/goods/good7.png',
		type: 'Декоративный',
		name: 'Сфера',
		old_price: 1990,
		new_price: 1094,
	},

	{
		id: 'good8',
		brend: 'BeForYou',
		material: 'Силикон; ABS-пластик',
		classes: 'baby distance usb',
		img: 'img/goods/good8.png',
		type: 'Детский',
		name: 'Зайчик',
		old_price: 1500,
		new_price: 1071,
	},

	{
		id: 'good9',
		brend: 'Artandwood',
		material: 'Акрил',
		classes: 'baby neon distance',
		img: 'img/goods/good9.png',
		type: 'Неоновый',
		name: 'Ловец снов',
		old_price: 2050,
		new_price: 1230,
	},

	{
		id: 'good10',
		brend: 'Lucia',
		material: 'Дерево, текстиль',
		classes: 'lamp',
		img: 'img/goods/good10.png',
		type: 'Абажур',
		name: 'Онтарио',
		old_price: 2590,
		new_price: 1049,
	},

	{
		id: 'good11',
		brend: 'Apeyron',
		material: 'Пластик',
		classes: 'candles',
		img: 'img/goods/good11.png',
		type: 'Светодиодные',
		name: 'Свечи',
		old_price: 468,
		new_price: 257,
	},

	{
		id: 'good12',
		brend: 'Saltway',
		material: 'Дерево, пластик, гималайская соль',
		classes: 'salt',
		img: 'img/goods/good12.png',
		type: 'Солевая лампа',
		name: 'Угли',
		old_price: 3716,
		new_price: 2126,
	},

	{
		id: 'good13',
		brend: 'TimeToCreate',
		material: 'Пластик',
		classes: 'three_d baby projector distance',
		img: 'img/goods/good13.png',
		type: 'Проектор',
		name: 'Новогодний',
		old_price: 4000,
		new_price: 1760,
	},

	{
		id: 'good14',
		brend: 'Hasbender',
		material: 'Стекло',
		classes: 'three_d distance',
		img: 'img/goods/good14.png',
		type: '3D-ночник',
		name: 'Зеркальная ваза',
		old_price: 5200,
		new_price: 2744,
	},

	{
		id: 'good15',
		brend: 'Organika',
		material: 'Гранулированный воск',
		classes: 'candles',
		img: 'img/goods/good15.png',
		type: 'Насыпные',
		name: 'Свечи',
		old_price: 3852,
		new_price: 1943,
	},

	{
		id: 'good16',
		brend: 'LaLava',
		material: 'Стекло',
		classes: 'lava',
		img: 'img/goods/good16.png',
		type: 'Лава-лампа',
		name: 'Сосулька',
		old_price: 2990,
		new_price: 1992,
	},

	{
		id: 'good17',
		brend: 'MullerHaus',
		material: 'Сплав алюминия',
		classes: 'projector distance',
		img: 'img/goods/good17.png',
		type: 'Проектор',
		name: 'Закат',
		old_price: 3572,
		new_price: 3291,
	},

	{
		id: 'good18',
		brend: 'LED TUBE',
		material: 'Пластик',
		classes: 'floor distance',
		img: 'img/goods/good18.png',
		type: 'Торшер',
		name: 'Угловой',
		old_price: 6000,
		new_price: 2881,
	},
]